#!/system/bin/sh
socket_opened=$(netstat -lnt | grep -e 0.0.0.0:5009 -e :::5009)
if [[ ! -z "$socket_opened" ]]
then
    if [[ $# -eq 0 ]]
    then
        echo "No argument supplied"
        remote-process localhost 5009 help
    else
        remote-process localhost 5009 "$@"
    fi
else
        echo "The route manager PFW remote-processor is not running"
fi

