#!/system/bin/sh
socket_opened=$(netstat -l | grep 0.0.0.0:5000)
if [[ ! -z "$socket_opened" ]]
then
    if [[ $# -eq 0 ]]
    then
        echo "No argument supplied"
        remote-process localhost 5000 help
    else
        remote-process localhost 5000 "$@"
    fi
else
        echo "The audio PFW remote-processor is not running"
fi

